name: simple-github-gcp-wif
on: workflow_dispatch

jobs:
  Job-One:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: 'read'
    steps:
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/427443496167/locations/global/workloadIdentityPools/github-gcp-wif/providers/github-provider'
          service_account: 'github-gcp-wif@mess-up-laoy.iam.gserviceaccount.com'

      - name: list compute instances
        run: |
          gcloud compute instances list
          gcloud compute instances create instance-1 --machine-type=n1-standard-1 --zone=us-central1-b --preemptible --no-restart-on-failure --maintenance-policy=terminate --project=mess-up-laoy

