name: simple-github-gcp-wif
on: workflow_dispatch

jobs:
  Job-One:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: 'read'
    steps:
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_WIF_SA }}'

      - name: list compute instances
        run: |
          gcloud compute instances list
          gcloud compute instances create instance-xx --project=mess-up-laoy --zone=us-central1-a --machine-type=n1-standard-1 --network-interface=subnet=default,no-address --shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring
