name: github-gcp-workload-identity-federations
on: workflow_dispatch
jobs:
  Job-One:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: 'read'
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo ${ACTIONS_ID_TOKEN_REQUEST_URL} > tmp/url.txt
      - shell: bash
        run: echo ${ACTIONS_ID_TOKEN_REQUEST_TOKEN} > tmp/token.txt
      - id: idtoken
        shell: bash
        run: |
          token=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
          runtimeUrl=${ACTIONS_ID_TOKEN_REQUEST_URL}
          runtimeUrl="${runtimeUrl}&audience=google-wlif"
          ID_TOKEN=$(curl -H "Authorization: bearer ${token}" ${runtimeUrl} | jq -r ".value")
          echo ::set-output name=idtoken::$ID_TOKEN
          echo $ID_TOKEN > tmp/idtoken.txt
      - name: Read idtoken
        id: githubtoken
        uses: juliangruber/read-file-action@v1
        with:
          path: tmp/idtoken.txt
      - name: Echo githubtoken
        run: echo "${{ steps.githubtoken.outputs.content }}"
